name: Other Talisman Secrets Scan

on: [push, pull_request]

jobs:
  talisman_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Talisman Secrets Scan
      uses: carhartl/talisman-secrets-scan-action@main
